spring.application.name: cards
server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active: "prod"

build.version: 3.0

cards:
  message: "Welcome to EazyBank cards related local APIs"
  contactDetails:
    name: "Sara Kim"
    email: "sara@eazybank.com"
  onCallSupport:
    - (551) 555-5431
    - (551) 523-5134